---
- hosts: my_vm
  become: yes
  tasks:
    - name: Pull MySQL Docker image for Daim
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container for Daim
      community.docker.docker_container:
        name: mysql-daim
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
        ports:
          - "3307:3306"

    - name: Pull Zabbix Docker image for Daim
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container for Daim
      community.docker.docker_container:
        name: zabbix-daim
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8093:80"
          - "10055:10051"
        env:
          DB_SERVER_HOST: "mysql-daim"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
          MYSQL_DATABASE: "zabbix"

    - name: Pull Nagios Docker image for Daim
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container for Daim
      community.docker.docker_container:
        name: nagios-daim
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8094:80"

    - name: Pull Prometheus Docker image for Daim
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container for Daim
      community.docker.docker_container:
        name: prometheus-daim
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8095:9090"
